name: Docker Build & Push (brotea-landing)

on:
  push:
    branches: [ "main" ]
  # Programar build diario (opcional)
  schedule:
    - cron: '30 14 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(grep -oP '(?<="version": ")[^"]*' package.json)
          echo "Encontrada versión: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Ajusta el nombre del repositorio a broteaconnect/brotea-landing
          tags: |
            broteaconnect/brotea-landing:latest
            broteaconnect/brotea-landing:${{ steps.version.outputs.version }}
